version: '3.9'
services:
  server:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
      args:
        TARGET: server
    container_name: server
    command: sh -c "cd server && npm run start:dev"
    env_file:
      - server/.env
    environment:
      TZ: Asia/Seoul
      ENVIRONMENT: development
      NODE_ENV: development
    ports:
      - 4000:4000
    volumes:
      - ./server/src/:/app/server/src
      - ./server/tsconfig.json:/app/server/tsconfig.json
      - ./server/tsconfig.build.json:/app/server/tsconfig.build.json
      - ./server/package.json:/app/server/package.json
      - ./server/nest-cli.json:/app/server/nest-cli.json
      - ./server/.env:/app/server/.env
  client:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
      args:
        TARGET: client
    container_name: client
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_HOST=http://server:4000
    volumes:
      - ./client/src:/app/client/src
      - ./client/package.json:/app/client/package.json
