FROM node:16.20-slim

ARG TARGET
ENV TARGET=${TARGET}

RUN apt-get update
RUN apt-get install -y procps

WORKDIR /app

COPY ./${TARGET} /app/${TARGET}

RUN cd ${TARGET} && npm ci

CMD cd ${TARGET} && npm start