version: '3.9'
services:
  test-server:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
      args:
        TARGET: server
    container_name: test-server
    command: sh -c "cd server && npm run start:dev"
    env_file:
      - server/.env
    environment:
      TZ: Asia/Seoul
      ENVIRONMENT: development
      NODE_ENV: development
    ports:
      - 4000:4000
    volumes:
      - ./server/src/:/app/server/src
      - ./server/tsconfig.json:/app/server/tsconfig.json
      - ./server/tsconfig.build.json:/app/server/tsconfig.build.json
      - ./server/package.json:/app/server/package.json
      - ./server/nest-cli.json:/app/server/nest-cli.json
      - ./server/.env:/app/server/.env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  test-client:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
      args:
        TARGET: client
        REACT_APP_SERVER_HOST: http://test-server:4000
    container_name: test-client
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_HOST=http://test-server:4000
    volumes:
      - ./client/src:/app/client/src
      # - ./client/package.json:/app/client/package.json
    depends_on:
      - test-server
